apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-list-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-list-app
  template:
    metadata:
      labels:
        app: nestjs-list-app
    spec:
      containers:
        - name: nestjs-list-app
          image: nestjs-list-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
