apiVersion: v1
kind: Service
metadata:
  name: nestjs-list-app-service
spec:
  selector:
    app: nestjs-list-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
